### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Pimmetje** [fvanroie/MqttClientPlugin#2]
I have the feeling i am doing something wrong. But as i am not used to VS. I have no clue 

The NUGet packages seems ok. But i am getting the following errors
```
Description
File 'C:\temp\MqttClientPlugin\bin\x64\Debug\MqttClient.dll' not found or not a PE file
The command ""C:\temp\MqttClientPlugin\API\DllExporter.exe" "Debug" "x64" "C:\temp\MqttClientPlugin\bin\x64\Debug\\" "MqttClient.dll"
if Debug == Release powershell.exe -Version 5.1  C:\temp\MqttClientPlugin\BuildTools\Build-RainmeterSkin.ps1 -TargetPath "C:\temp\MqttClientPlugin\bin\x64\Debug\MqttClient.dll" -PlatformName "x64" -SolutionDir  "C:\temp\MqttClientPlugin\\" -Skin Mqtt
" exited with code 1.
The command "powershell C:\temp\MqttClientPlugin\\BuildTools\New-BuildVersion.ps1" exited with code 1.
Unable to disassemble!
```

Thanks for your work!

**Comment by fvanroie** [comment]
Hello Pimmetjes,

Thank you for the reported build issue. Could you do a `git pull` and try again please?
That PowerShell error should now be fixed.

**Comment by Pimmetje** [comment]
Thanks for the fast reply.

I did a clean checkout on branch v0.1.29. I still receive more or less the same error. 

```
Description
The command ""C:\temp\MqttClientPlugin\API\DllExporter.exe" "Debug" "x64" "C:\temp\MqttClientPlugin\bin\x64\Debug\\" "MqttClient.dll"" exited with code 1.
The command "powershell C:\temp\MqttClientPlugin\\BuildTools\New-BuildVersion.ps1" exited with code 1.
File 'C:\temp\MqttClientPlugin\bin\x64\Debug\MqttClient.dll' not found or not a PE file
Unable to disassemble!
```

**Comment by fvanroie** [comment]
Indeed, there was still a reference to a missing BuildScript.
Now I updated the 0.1.29 branch, can you pull and build that source again please?
If it doesn't work, just delete the local copy and git clone the sources again.

Thanks.

**Comment by Pimmetje** [comment]
We are getting closer but where not yet there.
```
Description
A numeric comparison was attempted on "$(MsBuildMajorVersion)" that evaluates to "" instead of a number, in condition "($(MsBuildMajorVersion) < 16)".
The command ""C:\temp\MqttClientPlugin\API\DllExporter.exe" Debug x64 C:\temp\MqttClientPlugin\bin\x64\Debug\ MqttClient.dll" exited with code 1.
File 'C:\temp\MqttClientPlugin\bin\x64\Debug\MqttClient.dll' not found or not a PE file
Unable to disassemble!
```

**Comment by fvanroie** [comment]
Seems a Clean Solution + Rebuild Solution is needed after Restoring NuGet Packages...
Can you do Clean Solution and then Rebuild Solution ?

**Comment by Pimmetje** [comment]
Yes it seems to work now. Thanks a lot!
